### PR TITLE
feat: Release channel filter on apps endpoint

### PR DESCRIPTION
**Pull request by erikarenhill**
Added a query-parameter filter option on the v1 apps endpoint with default fallback to Stable channel. As this is mere a filtering option I decided to not implement this feature into a v2 endpoint.

DHIS2 instances could therefore just add ?channel=Canary to the appstore backend url to switch to Canary channel for example

### CODE REVIEW

**Comment by erikarenhill** [comment]
@varl Hmm, I think this feature could be merged, however we need to revisit how to handle this against the app management app, since that only has the base url and could not use querystrings. Then we would need to also provide something like appstore.api.channel next to appstore.api.version config

**Comment by varl** [comment]
> @varl Hmm, I think this feature could be merged, however we need to revisit how to handle this against the app management app, since that only has the base url and could not use querystrings. Then we would need to also provide something like appstore.api.channel next to appstore.api.version config

You mean that this would be configured per instance in `dhis.conf` to use e.g. canary or development builds only?

**Comment by erikarenhill** [comment]
> > @varl Hmm, I think this feature could be merged, however we need to revisit how to handle this against the app management app, since that only has the base url and could not use querystrings. Then we would need to also provide something like appstore.api.channel next to appstore.api.version config
> 
> You mean that this would be configured per instance in `dhis.conf` to use e.g. canary or development builds only?

Either that, or managed by adding a filter in the app management app where you could select release channel, then we just need a v2 endpoint to fetch existing channels and their names

**Comment by varl** [comment]
I think that it would be more powerful to be able to pick and choose which apps to run on stable and which to run on development. That should also allow users to use e.g. the stable and canary version side-by-side (if they want that).

**Comment by erikarenhill** [comment]
> I think that it would be more powerful to be able to pick and choose which apps to run on stable and which to run on development. That should also allow users to use e.g. the stable and canary version side-by-side (if they want that).

I see the point where someone want to use one single app from canary (to try it out) but the rest of the apps from Stable, and then using the channel in dhis.conf would be a bad choice. I was just about to edit my previous comment when I saw your response. Yes this is the way to go.

**Comment by erikarenhill** [comment]
Either way, this PR supports moving towards that goal and is also backwards compatible

**Pull request merged**
